### ISSUE TITLE
Space characters in username

### ISSUE THREAD

**Issue by tudalex** [rosedu/vmchecker#86]
Space characters can be inserted in the username at the beginning and at the end.
They are treated as different usernames and two account appear in the results list.

**Comment by calin-iorgulescu** [comment]
This is fixed in #70 . Before, the UI would simply send the user's info to the vmchecker service and receive an OK/FAIL reply if the credentials were good. Unfortunately, this meant that if "    username" was accepted by LDAP, then the UI would record that as the username. In #70, the actual user id is sent back to the UI, meaning that even if the user enters "    username", the service will send back the actual user id of "username", which will then further be used by all the operations. This eliminates the risk of having duplicate users.

Edit: This is a duplicate of issue #44 .

**Comment by tudalex** [comment]
Sorry, I though vmchecker.cs.pub.ro had the latest version deployed.
